### ISSUE TITLE
Missing reference Emotionlib.dll

### ISSUE THREAD

**Issue by shivanandugalat** [EmotionEngineer/EmotionPlayer#1]
Hi, there is missing reference for the dll Emotionlib.dll . Because of which while running its unable to load it.

**Comment by EmotionEngineer** [comment]
@shivanandugalat Hey! The DLL you need comes in the archive with the release. 
Here: https://github.com/EmotionEngineer/EmotionPlayer/releases/tag/v1.0
Try it and let me know.

**Comment by shivanandugalat** [comment]
Thanks got it.
